### ISSUE TITLE
PropCNF35 dataset from the ICLR paper

### ISSUE THREAD

**Issue by asuvarna31** [reactive-systems/deepltl#1]
Hi, 
I am trying to replicate the results from your paper and I see that PropCNF35 dataset is mentioned in the paper but not in the repository. Can you direct me to this dataset ?

**Comment by annaproxy** [comment]
Same goes for the 'LTLPattern126' dataset and the unsolved LTL dataset, are any of these available somewhere?

**Comment by realChrisHahn2** [comment]
Hi,

sorry for the late reply.
If the automatic downloading of the datasets is not working anymore or we missed something, please let us know.
You can also drop me an email anytime.

You can download the datasets directly from the following links as well.

PropCNF35
- train: https://storage.googleapis.com/deepltl_data/data/sat/neurosat-na-5-pk0.9-pg0.75-nf-990k-lbt-sat/train.txt
- test: https://storage.googleapis.com/deepltl_data/data/sat/neurosat-na-5-pk0.9-pg0.75-nf-990k-lbt-sat/test.txt
- val: https://storage.googleapis.com/deepltl_data/data/sat/neurosat-na-5-pk0.9-pg0.75-nf-990k-lbt-sat/val.txt

LTLPattern126:
- train: https://storage.googleapis.com/deepltl_data/data/ltl_traces/dac_concat_edge-na-6-ts125-nf-1p6m/train.txt
- test: https://storage.googleapis.com/deepltl_data/data/ltl_traces/dac_concat_edge-na-6-ts125-nf-1p6m/test.txt
- val: https://storage.googleapis.com/deepltl_data/data/ltl_traces/dac_concat_edge-na-6-ts125-nf-1p6m/val.txt

LTLUnsolved254: https://storage.googleapis.com/deepltl_data/data/ltl_traces/dac_timeouts-ts254/test.txt
